services:

  test_web_app:
    container_name: test_web_app
    build:
      dockerfile: Dockerfile
    image: testwebapp
    ports:
      - 8081:8080
      - 9010:9010
    environment:
      TZ: Europe/Moscow
