name: ci

on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Шаг для получения кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка JDK (укажите нужную версию Java)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Даем права на выполнение gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Сборка проекта Gradle
      - name: Build with Gradle
        run: ./gradlew build

      - name: Verify JAR exists
        run: |
          echo ------------
          pwd
          echo ------------       
          ls -la
          echo ------------        
          ls -la build/libs/
          echo ------------          
          test -f build/libs/TestWebProject.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_PROJECT_NAME }}:latest
